---
config_dir: '~'

# Default password for student users
userpass: '123456'

# Enable ping
ping_enable: true

# Change user password
changepwd_enable: true

# Change Hostname of pi
changehostname_enable: true

# Create student users based off of hostname
createusers_enable: true

# Upgrade from buster to bullseye
bullseye_enable: true

# Disable autologin
disableautologin_enable: true

# Update apt
aptupdate_enable: true

# Install gcc-8
gcc8_enable: true

# Upgrade apt
aptupgrade_enable: true

# Packages
packages_enable: true

# Reboot
reboot_enable: true
