---
config_dir: '~'

##
#  setup.yml
##

# Escalate SSH keys to root in lab_pi's
setuproot_enable: true

##
#  pi-setup.yml
##

# Default password for student users
userpass: '123456'

# Change user password
changepwd_enable: true

# Change Hostname of pi
changehostname_enable: true

# Create student users based off of hostname
createusers_enable: true

# Disable autologin
disableautologin_enable: true

# Update apt & upgrade packages
update_enable: true

# Install recommended packages
packages_enable: true

# Reboot
reboot_enable: true
