---
- hosts: all            
  become: yes
  tasks:
    - name: Change user password
      user:
        name: pi
        update_password: always
        password: "{{ newpassword|password_hash('sha512') }}"
        
    - name: Upgrade from buster to bullseye
      ansible.builtin.shell: |
        sed -i 's/buster/bullseye/g' /etc/apt/sources.list
        sed -i 's/buster/bullseye/g' /etc/apt/sources.list.d/raspi.list

    - name: Disable Autologin
      ansible.builtin.shell: |
        sed -i 's/^greeter-hide-users=true/greeter-hide-users=false/g' /etc/lightdm/lightdm.conf
        sed -i 's/^\#greeter-allow-guest=true/greeter-allow-guest=false/g' /etc/lightdm/lightdm.conf
        sed -i 's/^\#greeter-show-manual-login=false/greeter-show-manual-login=true/g' /etc/lightdm/lightdm.conf
        sed -i 's/^\#allow-guest=true/allow-guest=false/g' /etc/lightdm/lightdm.conf
        sed -i 's/^\#allow-guest=true/allow-guest=false/g' /etc/lightdm/lightdm.conf
        sed -i 's/^\#autologin-user-timeout=0/autologin-user-timeout=10/g' /etc/lightdm/lightdm.conf
        sed -i 's/^autologin-user=pi/\#autologin-user=pi/g' /etc/lightdm/lightdm.conf

    - name: Update apt        
      apt:
        update_cache: yes

# I presume this is temporary - needed for transitioning from buster to bullseye
    - name: Install gcc-8-base
      apt:
        state: latest
        pkg:
        - gcc-8-base

    - name: Upgrade apt
      apt:
        upgrade: full

    - name: Install some packages
      apt:
        install_recommends: yes
        pkg:
        - php-mysql
        - php
        - mariadb-server
        - cockpit

    - name: Reboot
      reboot:
